FROM node:18

WORKDIR /usr/src/m1

COPY package*.json ./

RUN apt-get update && apt-get -y dist-upgrade
RUN apt install -y netcat-traditional

RUN npm install

COPY . .

COPY wait-for.sh /wait-for.sh

RUN chmod +x /wait-for.sh